({
	onKo: function(spot) {},
	onSendOut: function(spot, previndex) {},
	onSendBack: function(spot) {},
	onUseAttack: function(spot, attack) {},
	onBeginTurn: function(turn) {},
	onHpChange: function(spot, newHp) {},
	onHitCount: function(spot, count) {},
	onEffectiveness: function(spot, effectiveness) {},
	onCriticalHit: function(spot) {},
	onMiss: function(spot) {},
	onAvoid: function(spot) {},
	onStatBoost: function(spot, stat, boost) {},
	onMajorStatusChange: function(spot, status) {},
	onPokeballStatusChanged: function(player, poke, status) {},
	onStatusAlreadyThere: function(spot, status) {},
	onStatusNotification: function(spot, status) {},
	onStatusDamage: function(spot, status) {},
	onStatusOver: function(spot, status) {},
	onAttackFailing: function(spot) {},
	onPlayerMessage: function(spot) {},
	onSpectatorJoin: function(id) {},
	onSpectatorLeave: function(id) {},
	onSpectatorChat: function(id) {},
	onMoveMessage: function(spot, move, part, type, foe, other) {},
	onNoTarget: function(spot) {},
	onItemMessage: function(spot, item, part, foe, berry, other) {},
	onFlinch: function(spot) {},
	onRecoil: function(spot) {},
	onDrained: function(spot) {},
	onStartWeather: function(spot, weather) {},
	onContinueWeather: function(weather) {},
	onEndWeather: function(weather) {},
	onHurtWeather: function(spot, weather) {},
	onDamageDone: function(spot, damage) {},
	onAbilityMessage: function(spot, ab, part, type, foe, other) {},
	onSubstituteStatus: function(spot) {},
	onBlankMessage: function() {},
	onClauseActivated: function(clause) {},
	onRatedNotification: function(bool rated) {},
	onTierNotification: function(tier) {},
	onDynamicInfo: function(spot) {},
	onPokemonVanish: function(spot) {},
	onPokemonReappear: function(spot) {},
	onSpriteChange: function(spot, newSprite) {},
	onDefiniteFormeChange: function(spot, poke, newPoke) {},
	onCosmeticFormeChange: function(spot, subforme) {},
	onClockStart: function(player, time) {},
	onClockStop: function(player, time) {},
	onShiftSpots: function(player, spot1, spot2) {},
	onBattleEnd: function(res, winner) {},
	onPPChange: function(spot, move, PP) {},
	onOfferChoice: function(player) {},
	onTempPPChange: function(spot, move, PP) {},
	onMoveChange: function(spot, slot, move) {},
	onRearrangeTeam: function(player) {},
	onChoiceSelection: function(player) {},
	onChoiceCancellation: function(player) {},
	onVariation: function(player, bonus, malus) {},
	onDynamicStats: function(spot) {},
	onPrintHtml: function(html) {},
	onReconnect: function(player) {},
	onDisconnect: function(player) {},
	onAttackChosen: function(spot, attackSlot, target) {},
	onSwitchChosen: function(spot, pokeSlot) {},
	onTeamOrderChosen: function(player) {},
	onChoiceCancelled: function(player) {},
	onShiftToCenterChosen: function(player) {},
	onDrawRequest: function(player) {},
})
